on:
  push:
    tags:
      - 'test-mail'

jobs:
  send_test_email_job:
    runs-on: ubuntu-latest
    name: a job to send a testing email
    steps:
      - name: 'Create env file'
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: sending test email
        id: test-email
        uses: LukaHuang/mailchimp-github-action@v0.4